# Generated by Django 4.2.14 on 2024-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, verbose_name="Name")),
                ("Email", models.CharField(max_length=50, verbose_name="Email")),
                ("Username", models.CharField(max_length=50, verbose_name="Username")),
                ("Password", models.CharField(max_length=50, verbose_name="Password")),
            ],
        ),
    ]
