# Generated by Django 4.2.14 on 2024-08-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="IsAdmin",
            field=models.BooleanField(default=False, verbose_name="is admin ?"),
        ),
    ]
